spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 9 # (4*2)+1
      read-only: false #只读数据库
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 5
      max-idle: 2
      max-wait: 10000
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: del_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
